// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluAWoNTkZteHJDXV3aC2iMd6Yf5MtFwk',
    appId: '1:516703918700:web:your-web-app-id',
    messagingSenderId: '516703918700',
    projectId: 'etf-flow',
    authDomain: 'etf-flow.firebaseapp.com',
    storageBucket: 'etf-flow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluAWoNTkZteHJDXV3aC2iMd6Yf5MtFwk',
    appId: '1:516703918700:android:your-android-app-id',
    messagingSenderId: '516703918700',
    projectId: 'etf-flow',
    storageBucket: 'etf-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAluAWoNTkZteHJDXV3aC2iMd6Yf5MtFwk',
    appId: '1:516703918700:ios:d5619926a4b45b8bee9649',
    messagingSenderId: '516703918700',
    projectId: 'etf-flow',
    storageBucket: 'etf-flow.firebasestorage.app',
    iosBundleId: 'com.sly13.etfTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAluAWoNTkZteHJDXV3aC2iMd6Yf5MtFwk',
    appId: '1:516703918700:ios:d5619926a4b45b8bee9649',
    messagingSenderId: '516703918700',
    projectId: 'etf-flow',
    storageBucket: 'etf-flow.firebasestorage.app',
    iosBundleId: 'com.sly13.etfTracker',
  );
}
