-- AlterTable
ALTER TABLE "public"."sol_flow" 
ADD COLUMN IF NOT EXISTS "vanEck" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "fidelity" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "twentyOneShares" DOUBLE PRECISION;

